### ISSUE TITLE
update notification seems to not work on "initial" run / CSCLSROZ-445

### ISSUE THREAD

**Issue by SabrinaEspino** [Accenture/sfmc-devtools#31] opened 2021-05-05 16:15 UTC
it seems the way the "last checked" time is compared it currently fails on "first check".
lets make sure we also run this on whatever first run we execute to ensure old but never used installs produce immediate update notifications

likely requires an update of the dependency itself rather than one inside of catalyst

**Comment by JoernBerkefeld** [comment] 2022-02-23 07:23
could be resolved by #94

**Comment by JoernBerkefeld** [comment] 2022-03-30 14:07
closing as duplicate of #94

**Closed by JoernBerkefeld** 2022-03-30 14:07 UTC
Labels: bug, duplicate, e/IDE
