### ISSUE TITLE
[BUG] Mcdev strips content before and after script tag upon retrieval

### ISSUE THREAD

**Issue by Beryl-18** [Accenture/sfmc-devtools#1157] opened 2024-01-03 12:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I recently tried pulling a code snippet, metadata would be asset. This code snippet contains html, ampscript and ssjs script. as of now, when retrieving such code snippets, all the content except the content within the ssjs tags would be lost

### Steps To Reproduce

1. Have a content block/code snippet with such content - including html, ampscript, ssjs within.
2. mcdev retrieve this asset using customer key
3. Done. When inspecting the file that has been retrieved, you'd find that the content before the `<script runat="server"> `tag is missing and the same with content after the `</script> `tag.

### Version

6.0.0

### Environment

MacOS, but this doesn't matter. Node and mcdev are of the latest versions. 

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by JoernBerkefeld** [comment] 2024-01-08 14:38
i can confirm the bug. tried it with a content block consisting of:

```html
<div>
my 1st HTML
</div>

%%[ /* my ampscript */ ]%%

<script runat="server">
// my ssjs
</script>

<div>
  my 2nd HTML
</div>
```

the API returns that as:

```
<table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="min-width: 100%; " class="stylingblock-content-wrapper"><tr><td class="stylingblock-content-wrapper camarker-inner"><div>\n  my 1st html\n</div>\n\n%%[ /* my ampscript */ ]%%\n\n<script runat="server">\n// my ssjs\n</script>\n\n<div>\n  my 2nd html\n</div></td></tr></table>
```

and mcdev saves it as 

```html
// my ssjs

```

**Comment by JoernBerkefeld** [comment] 2024-01-08 14:44
looks like the method that identifies ssjs code is using the multi-line flag for some reason which it shouldn't be - at least not for content blocks / assets

**Comment by JoernBerkefeld** [comment] 2024-01-08 16:32
will be released together with a couple other fixes soon. likely as 6.0.1 or 6.1.0

**Comment by JoernBerkefeld** [comment] 2024-01-08 16:33
oh and, thank you for reporting this @Beryl-18 :-)

**Closed** 2024-01-08 16:32 UTC
Labels: bug, c/asset
